name: Claris Li
description: stuff I learn
meta_description: "Claris Li, stuff I learn"

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
domain_name: 'https://clarisli.github.io/'
google_analytics: 'UA-141713062-1'
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url:            'https://clarisli.github.io/'
author:         'Claris Li'
